### ISSUE TITLE
数据库文件没更新吧？

### ISSUE THREAD

**Issue by single-cong** [BuRNIngsuperman/LetaoMall#1]
SELECT user_id,nick_name,login_name,password,introduce_sign,address,is_deleted,locked_flag,create_time FROM usr_user    WHERE login_name = ?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'nick_name' in 'field list'

是不是数据库sql文件没更新啊兄弟

**Comment by BuRNIngsuperman** [comment]
sql文件更新了
